# Pragmas.
use strict;
use warnings;

# Modules.
use ExtUtils::MakeMaker;

# Definition.
WriteMakefile(
	'AUTHOR' => 'Michal Špaček <skim@cpan.org>',
	'BUILD_REQUIRES' => {
		'English' => 0,
		'File::Object' => 0,
		'Test::More' => 0,
		'Test::Pod' => 0,
		'Test::Pod::Coverage' => 0,
	},
	'CONFIGURE_REQUIRES' => {
		'ExtUtils::MakeMaker' => 0,
	},
	'NAME' => 'Pod::Example',
	'PREREQ_PM' => {
		'Class::Utils' => 0.01,
		'English' => 0,
		'Error::Pure' => 0.01,
		'Module::Info' => 0,
		'Pod::Abstract' => 0,
	},
	'VERSION' => '0.01',
	'test' => {
		'TESTS' => 't/Pod::Example/*.t',
	},
);
