---
abstract: 'Module for getting example from POD.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.42
  File::Object: 0.01
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Example
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 0
  Module::Info: 0
  Pod::Abstract: 0
  Readonly: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository:
    type: git
    url: git://github.com/tupinek/Pod-Example
    web: https://github.com/tupinek/Pod-Example
version: 0.01
